- Verifiable Credentials JSON Schema Specification.md
I removed a few Workday-specific references. Open to suggestions to move forward.
> Initial draft

- .gitignore
- spec/index.bs
- spec/index.html
Copied over most of the text from the initial doc and bikeshedified as much as I could. Will probably need some assistance with setting up gh-pages.
> Bikeshed draft

- CODEOWNERS
- CONTRIBUTING.md
- LICENSE.md
Boilerplate files that got missed
> bug in create script caused me to miss these files

- spec/index.bs
> Fix broken link

- .pr-preview.json
- CODEOWNERS
- CODE_OF_CONDUCT.md
- LICENSE.md
- w3c.json
I have made some updates/changes on the repository to mold into the WG...
- Gabe, your github ID in the W3C space (linked from your profile) is @decentralgabe, so I changed in the CODEOWNERS file. You should, if possible, use this github persona, otherwise we get into conflcts with our tools
- I have updated the LICENSE file, and copied the w3c.json and CODE_OF_CONDUCT files from other repos. All admin things.
- I see you use bikeshed instead of respec. I did copy the preview file and set it to use bikeshed, but I wonder if you could consider moving to respec instead (I know it is a pain). This WG, and that includes myself, have been using respec only and, at least that is my case, have no experience in using bikeshed. This may affect setting up automatic publishing, making PR-s, etc. To …
> Initial setup

- docs/index.html
- v2/index.bs
- update status to cg final
- handle rename to make `vc-json-schema` singular
> update status to cg final

- index.html
fixes https://github.com/w3c/vc-json-schema/pull/138#discussion_r1188892781
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/139.html" title="Last updated on May 10, 2023, 4:08 AM UTC (ba39eb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/139/bf2be26...ba39eb3.html" title="Last updated on May 10, 2023, 4:08 AM UTC (ba39eb3)">Diff</a>
> Remove informative RECOMMENDED

- CODEOWNERS
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/150.html" title="Last updated on May 15, 2023, 9:07 PM UTC (f551bc3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/150/dbfac75...f551bc3.html" title="Last updated on May 15, 2023, 9:07 PM UTC (f551bc3)">Diff</a>
> Added myself as editor

- README.md
- index.html
fixes #144, #145
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/149.html" title="Last updated on May 16, 2023, 3:15 AM UTC (3e6c30b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/149/dbfac75...3e6c30b.html" title="Last updated on May 16, 2023, 3:15 AM UTC (3e6c30b)">Diff</a>
> remove metadata; types for credential and non-credential; add issue tags

- FPWD/2023-05-23/index.html
- common.js
- index.html
Addresses feedback in https://github.com/w3c/transitions/issues/507
Also fix #154
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/155.html" title="Last updated on May 18, 2023, 5:33 PM UTC (3fcae53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/155/7eaa9b9...3fcae53.html" title="Last updated on May 18, 2023, 5:33 PM UTC (3fcae53)">Diff</a>
> Update FPWD from feedback

- index.html
fixes #147 and #148
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/169.html" title="Last updated on Jun 22, 2023, 10:31 PM UTC (36870a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/169/5b8a09d...36870a9.html" title="Last updated on Jun 22, 2023, 10:31 PM UTC (36870a9)">Diff</a>
> add a11y and i18n text

- index.html
Fix #171
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/175.html" title="Last updated on Jul 13, 2023, 11:08 PM UTC (c5eeb2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/175/6cfae46...c5eeb2f.html" title="Last updated on Jul 13, 2023, 11:08 PM UTC (c5eeb2f)">Diff</a>
> Add details on JSON schema processing

- index.html
This PR fixes #19
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/187.html" title="Last updated on Jul 26, 2023, 5:23 PM UTC (4dd582f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/187/2743534...4dd582f.html" title="Last updated on Jul 26, 2023, 5:23 PM UTC (4dd582f)">Diff</a>
> Remove resolution section

- index.html
fix #178
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/192.html" title="Last updated on Aug 1, 2023, 10:40 PM UTC (f5a0e1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/192/64a7efa...f5a0e1d.html" title="Last updated on Aug 1, 2023, 10:40 PM UTC (f5a0e1d)">Diff</a>
> Remove year as a version

- index.html
Fixes #136
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/193.html" title="Last updated on Aug 9, 2023, 2:12 PM UTC (5d55a39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/193/6aae47c...5d55a39.html" title="Last updated on Aug 9, 2023, 2:12 PM UTC (5d55a39)">Diff</a>
> Added warning to avoid composition problems.

- common.js
- index.html
fix #157
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/198.html" title="Last updated on Aug 14, 2023, 5:43 PM UTC (ec30c54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/198/ab0a7f3...ec30c54.html" title="Last updated on Aug 14, 2023, 5:43 PM UTC (ec30c54)">Diff</a>
> Media types for plain json schema, JWT, and SD-JWT

- index.html
Fixes #201
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/209.html" title="Last updated on Aug 28, 2023, 4:23 PM UTC (bf930f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/209/eacebb3...bf930f6.html" title="Last updated on Aug 28, 2023, 4:23 PM UTC (bf930f6)">Diff</a>
> Discourage Unique tracking IDs

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-json-schema/pull/215.html" title="Last updated on Sep 7, 2023, 4:39 PM UTC (6809c94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/215/b99f2b5...TallTed:6809c94.html" title="Last updated on Sep 7, 2023, 4:39 PM UTC (6809c94)">Diff</a>
> fix a plural that should be singular

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/218.html" title="Last updated on Sep 27, 2023, 7:48 PM UTC (6d7c963)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/218/30a9a3e...6d7c963.html" title="Last updated on Sep 27, 2023, 7:48 PM UTC (6d7c963)">Diff</a>
> Add section on revision history

- CR/2023-11-07/index.html
- index.html
as per https://github.com/w3c/transitions/issues/573
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/219.html" title="Last updated on Oct 14, 2023, 7:13 PM UTC (f0c573d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/219/7f3ba85...f0c573d.html" title="Last updated on Oct 14, 2023, 7:13 PM UTC (f0c573d)">Diff</a>
> Update CR Date

- CR/2023-11-07/index.html
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/220.html" title="Last updated on Oct 17, 2023, 4:46 PM UTC (9fd91b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/220/95ed2d7...9fd91b2.html" title="Last updated on Oct 17, 2023, 4:46 PM UTC (9fd91b2)">Diff</a>
> Update SoTD text

- CR/2023-11-14/index.html
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/226.html" title="Last updated on Nov 7, 2023, 10:43 PM UTC (f9b9c88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/226/1f2cd01...f9b9c88.html" title="Last updated on Nov 7, 2023, 10:43 PM UTC (f9b9c88)">Diff</a>
> update CR date to November 14

- index.html
fixes #235
***
<a href="https://pr-preview.s3.amazonaws.com/mkhraisha/vc-json-schema/pull/240.html" title="Last updated on Jan 29, 2025, 5:21 PM UTC (656ac5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/240/b6878b3...mkhraisha:656ac5c.html" title="Last updated on Jan 29, 2025, 5:21 PM UTC (656ac5c)">Diff</a>
> add ref example

- index.html
fixes #236
***
<a href="https://pr-preview.s3.amazonaws.com/mkhraisha/vc-json-schema/pull/241.html" title="Last updated on Jan 29, 2025, 4:29 PM UTC (c90684e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/241/b6878b3...mkhraisha:c90684e.html" title="Last updated on Jan 29, 2025, 4:29 PM UTC (c90684e)">Diff</a>
> update media types

- schema/json-schema-credential-schema.json
> update credentialSchema id to align with spec text

- CODEOWNERS
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/mkhraisha/vc-json-schema/pull/244.html" title="Last updated on Jan 29, 2025, 5:31 PM UTC (ea5e379)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/244/b6878b3...mkhraisha:ea5e379.html" title="Last updated on Jan 29, 2025, 5:31 PM UTC (ea5e379)">Diff</a>
> Update editors & codeowners
