w3c/vc-json-schema

- docs/index.html
- docs/schema/1.0/schema.json
- spec/index.bs
> fix cred schema links

- index.html
Added some guidance to address https://github.com/w3c/vc-json-schema/issues/122
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/138.html" title="Last updated on May 8, 2023, 1:46 PM UTC (dff29db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/138/45616b6...dff29db.html" title="Last updated on May 8, 2023, 1:46 PM UTC (dff29db)">Diff</a>
> Added guidance on type property relationship

- index.html
also added language on matching IDs when using credentialschema2023
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/160.html" title="Last updated on May 26, 2023, 4:55 PM UTC (c84785b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/160/ea0a047...c84785b.html" title="Last updated on May 26, 2023, 4:55 PM UTC (c84785b)">Diff</a>
> fix examples to be valid json

- index.html
fixes #166
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/168.html" title="Last updated on Jun 21, 2023, 7:00 PM UTC (87647ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/168/5b8a09d...87647ae.html" title="Last updated on Jun 21, 2023, 7:00 PM UTC (87647ae)">Diff</a>
> Add section addressing PII in schemas

- common.js
- index.html
fix #133
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/170.html" title="Last updated on Jul 5, 2023, 8:26 PM UTC (064c8f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/170/9a34f77...064c8f9.html" title="Last updated on Jul 5, 2023, 8:26 PM UTC (064c8f9)">Diff</a>
> Add normative references for 3 json schema versions

- index.html
- terms.html
as per discussion in https://github.com/w3c/vc-data-model/pull/1178
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/174.html" title="Last updated on Jul 11, 2023, 5:02 PM UTC (3677cf3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/174/6cfae46...3677cf3.html" title="Last updated on Jul 11, 2023, 5:02 PM UTC (3677cf3)">Diff</a>
> update credentialschema to verifiablecredentialschema

- index.html
Fixes #120
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/177.html" title="Last updated on Jul 25, 2023, 3:43 PM UTC (2a4bd83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/177/51bc8e7...2a4bd83.html" title="Last updated on Jul 25, 2023, 3:43 PM UTC (2a4bd83)">Diff</a>
> Added related resource text and example

- index.html
Fix #180
- Require implementers support the latest json schema version
- Add note around watching for the release of the 'stable' json schema version
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/184.html" title="Last updated on Jul 26, 2023, 3:33 PM UTC (c5e25d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/184/2743534...c5e25d7.html" title="Last updated on Jul 26, 2023, 3:33 PM UTC (c5e25d7)">Diff</a>
> Require at least one JSON Schema version

- index.html
- terms.html
Fix #172 #178 
I believe this needs a change to the core vocab to add a new property `jsonSchema` with the `type` as `@json`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/186.html" title="Last updated on Jul 26, 2023, 3:40 PM UTC (21ff4f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/186/2743534...21ff4f1.html" title="Last updated on Jul 26, 2023, 3:40 PM UTC (21ff4f1)">Diff</a>
> Update language around the defined types and their usages

- index.html
Fix #182
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/185.html" title="Last updated on Jul 26, 2023, 7:16 PM UTC (313dc88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/185/2743534...313dc88.html" title="Last updated on Jul 26, 2023, 7:16 PM UTC (313dc88)">Diff</a>
> Update term definitions according to the core vocab

- index.html
Fixes #176 by adding the RFC. The term definition for URL says we will not use the term IRI, so removed it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/188.html" title="Last updated on Jul 31, 2023, 7:19 PM UTC (38c46ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/188/2d2615f...38c46ad.html" title="Last updated on Jul 31, 2023, 7:19 PM UTC (38c46ad)">Diff</a>
> Rename IRI to URL and point to RFC

- index.html
fix #173
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/190.html" title="Last updated on Aug 1, 2023, 10:53 PM UTC (8200759)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/190/64a7efa...8200759.html" title="Last updated on Aug 1, 2023, 10:53 PM UTC (8200759)">Diff</a>
> Add guidance on when to use each type

- index.html
This aims to address #143 for VC claimsets (i.e. a VC without the proof piece being referenced.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/195.html" title="Last updated on Aug 7, 2023, 10:07 PM UTC (6062d4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/195/6aae47c...6062d4e.html" title="Last updated on Aug 7, 2023, 10:07 PM UTC (6062d4e)">Diff</a>
> Added validation examples.

- index.html
We had multiple examples of "Verifiable Credentials" that weren't conforming to VCDM 2.0. The previous respec plugin that we were using had the `vc` claim inside the JWT payload, which was VCDM 1.1 JWTs. 
This change makes it so all examples are VCDM 2.0 JWTs secured according to vc-jose-cose. It makes it easier for readers by having explicit examples of VCs that are secured.
In the future, we may want to add internally secured VCs as part of the examples.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 9, 2023, 7:39 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec …
> Change plugin to one that supports vc-jose-cose with VCDM 2.0

- index.html
- guidance on the id property
- requiring the use of the JsonSchema type and jsonSchema properties
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/199.html" title="Last updated on Aug 14, 2023, 10:24 PM UTC (f0bbbbe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/199/dc8c196...f0bbbbe.html" title="Last updated on Aug 14, 2023, 10:24 PM UTC (f0bbbbe)">Diff</a>
> Guidance on using JsonSchemaCredential

- index.html
- schema/json-schema-credential-schema.json
This fixed #159 by making it clear what the value of `credentialSchema` MUST be. This prevents any infinite recursions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/204.html" title="Last updated on Aug 18, 2023, 5:07 PM UTC (593929a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/204/2eda973...593929a.html" title="Last updated on Aug 18, 2023, 5:07 PM UTC (593929a)">Diff</a>
> Clarified the value of `credentialSchema` when type is JsonSchemaCredential

- index.html
Simple editorial change.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/205.html" title="Last updated on Aug 21, 2023, 7:04 PM UTC (334c791)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/205/f8f798d...334c791.html" title="Last updated on Aug 21, 2023, 7:04 PM UTC (334c791)">Diff</a>
> Updated the respec plugin version

- index.html
Fixes #203
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/207.html" title="Last updated on Aug 21, 2023, 5:35 PM UTC (305fb52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/207/07b4ae3...305fb52.html" title="Last updated on Aug 21, 2023, 5:35 PM UTC (305fb52)">Diff</a>
> Encourage OHTTP to prevent linking schema requests

- README.md
- index.html
- terms.html
Add href-able term definition for `jsonSchema`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/211.html" title="Last updated on Sep 6, 2023, 5:35 PM UTC (c1d214b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/211/9c37640...c1d214b.html" title="Last updated on Sep 6, 2023, 5:35 PM UTC (c1d214b)">Diff</a>
> Add test suite to readme; term definition for jsonschema

- README.md
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-json-schema/pull/214.html" title="Last updated on Sep 7, 2023, 4:11 PM UTC (a60c7e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/214/243c1a7...TallTed:a60c7e2.html" title="Last updated on Sep 7, 2023, 4:11 PM UTC (a60c7e2)">Diff</a>
> typo and language fixes

- common.js
- index.html
Address normative reference feedback from #210.
- Remove unused refs in `common.js`
- Rely on refs from existing specs instead of new refs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/212.html" title="Last updated on Sep 7, 2023, 6:18 PM UTC (0eb6dc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/212/243c1a7...0eb6dc0.html" title="Last updated on Sep 7, 2023, 6:18 PM UTC (0eb6dc0)">Diff</a>
> Address part of 210

- index.html
- terms.html
Fix #202
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/213.html" title="Last updated on Sep 6, 2023, 9:43 PM UTC (6b92bbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/213/9c37640...6b92bbd.html" title="Last updated on Sep 6, 2023, 9:43 PM UTC (6b92bbd)">Diff</a>
> Add privacy considerations around data minimization

- index.html
- Address remaining feedback in #210 relating to media types, json schema version references, and $id language
- Minor formatting updates
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/216.html" title="Last updated on Sep 13, 2023, 12:42 PM UTC (91dad89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/216/0b4d38e...91dad89.html" title="Last updated on Sep 13, 2023, 12:42 PM UTC (91dad89)">Diff</a>
> Address normative references issues

- CR/2023-11-07/index.html
- index.html
Minor editorial: missing '#' character.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/221.html" title="Last updated on Oct 22, 2023, 9:01 AM UTC (7c32244)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/221/8cacf18...7c32244.html" title="Last updated on Oct 22, 2023, 9:01 AM UTC (7c32244)">Diff</a>
> Missing fragment ID

- CR/2023-11-07/index.html
- index.html
fix #222
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/223.html" title="Last updated on Oct 29, 2023, 7:52 PM UTC (eb64b6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/223/a6fb13b...eb64b6f.html" title="Last updated on Oct 29, 2023, 7:52 PM UTC (eb64b6f)">Diff</a>
> i18n feedback

- EXPLAINER.md
- example/yaml-json-schema.yaml
- index.html
Fixes #224 by adding a `locale` field. 
Additionally, this PR also renames `name` in favor of `title`, because the latter is part of the json schema [spec](https://json-schema.org/understanding-json-schema/reference/annotations).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/225.html" title="Last updated on Nov 3, 2023, 12:04 AM UTC (7ccc3dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/225/1f2cd01...7ccc3dd.html" title="Last updated on Nov 3, 2023, 12:04 AM UTC (7ccc3dd)">Diff</a>
> Renamed `name` to `title` and added `lang` & `dir`.

- index.html
@decentralgabe should we also remove Orie on this PR or do you want that seperate?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/232.html" title="Last updated on Dec 15, 2023, 5:26 PM UTC (e27f766)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/232/7544c07...e27f766.html" title="Last updated on Dec 15, 2023, 5:26 PM UTC (e27f766)">Diff</a>
> add Mike Prorock to editor list

- index.html
Per https://github.com/w3c/vc-json-schema/issues/234 the following URL:
`https://www.w3.org/2022/credentials/v2/json-schema-credential-schema.json`
has now been replaced by 
`https://www.w3.org/ns/credentials/json-schema/v2.json`
This PR is just a global search and replace for those. The new URL is also alive (see  https://github.com/w3c/vc-json-schema/issues/234#issuecomment-2345376124).
@decentralgabe, I do not know whether there are other places in the spec (or other files) where a similar change should be done.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/pull/237.html" title="Last updated on Sep 12, 2024, 5:08 PM UTC (09ca120)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/237/84e8858...09ca120.html" title="Last updated on Sep …
> Correct the official schema URL

- example/yaml-json-schema.yaml
- index.html
- schema/json-schema-credential-schema.json
fixes #239 by removing all references to Schema Draft 2019 except in the Indeterminate evaluation section: 
***
<a href="https://pr-preview.s3.amazonaws.com/mkhraisha/vc-json-schema/pull/243.html" title="Last updated on Jan 25, 2025, 6:41 PM UTC (1466306)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-json-schema/243/b6878b3...mkhraisha:1466306.html" title="Last updated on Jan 25, 2025, 6:41 PM UTC (1466306)">Diff</a>
> remove references to older schema drafts
